import type { IncomingMessage } from 'node:http';
import type { Context } from '@deepseek-ai/cordis';
import type WebSocket from 'ws';
import type { VoiceConfig } from './config.ts';
import { TemporaryKeyService } from './temporary-key-service.ts';
import { VoiceRuntime } from './voice-runtime.ts';
/** Direct-media control plane. Binary/PCM frames are categorically forbidden. */
export declare class DirectControlConnection {
    private readonly ctx;
    private readonly socket;
    private readonly request;
    private readonly config;
    private readonly onClosed;
    private readonly runtime;
    private readonly temporaryKeys;
    private readonly provisionalId;
    private continuity;
    private direct;
    private hello;
    private coordinator;
    private functionBridge;
    private serverSeq;
    private closed;
    private ready;
    private leaseAcquired;
    private lastClientActivityAt;
    private functionQueue;
    private readonly helloTimer;
    private heartbeatTimer;
    constructor(ctx: Context, socket: WebSocket, request: IncomingMessage, config: VoiceConfig, onClosed: () => void, runtime: VoiceRuntime, temporaryKeys?: TemporaryKeyService);
    get id(): string;
    dispose(reason?: string): void;
    private receive;
    private start;
    private issueOffer;
    private refreshOffer;
    private mediaConnected;
    private mediaClosed;
    private executeFunctionCall;
    private enqueueFunctionCall;
    private answerApproval;
    private answerQuestion;
    private afterApprovalResolved;
    private afterQuestionResolved;
    private backendCallbacks;
    private recordBackendEvent;
    private replayBackendEvents;
    private retireBackendEvent;
    private sendBackendEvent;
    private ackBackendEvent;
    private sendApproval;
    private sendQuestion;
    private acceptMetrics;
    private assertActiveMedia;
    private checkControlHeartbeat;
    private fail;
    private send;
    private nextSeq;
}
